### PR TITLE
docs(ce-plugins): Add Contacts Plugin to misc section

### PR DESCRIPTION
**Pull request by Idrimi**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
the README says "Coming soon. The Android Support is not fully tested yet.". But I see actual code for Android. Does it support it or not?

**Comment by Idrimi** [comment]
> the README says "Coming soon. The Android Support is not fully tested yet.". But I see actual code for Android. Does it support it or not?

Hi it works, but as mentioned it's not properly tested and documented yet.

**Comment by jcesarmobile** [comment]
could you test and document it? we try to only add plugins that are supported on at leas iOS and Android (unless they are platform specific)

**Comment by Idrimi** [comment]
> could you test and document it? we try to only add plugins that are supported on at leas iOS and Android (unless they are platform specific)

sure. You can close the pull request. I will open a new one, as soon as it is tested and documented.

**Comment by Idrimi** [comment]
Closed: Will open a new one as soon as documentation and testing is done.

**Pull request closed without merging**
