### PR TITLE
[WIP] fix(layout): fix offset bottom on iOS devices (closes #337)

### LINKED ISSUE #337: Offset at the bottom after app launch on iOS devices
There is a small offset at the bottom of the webview directly after the splash-screen disappeared. On reals devices the offset quickly vanishes (see gif), in the simulator it stays. I've tried with the example app and with one of our apps (both are Ionic projects). It happens on the iPhoneX (where the offset is biggest) and other devices too (see screenshot).

```
@capacitor/cli: 1.0.0-alpha.13
@capacitor/core: 1.0.0-alpha.13
```

offset-iphonex

offset-sim-iphone8_x

### PR DESCRIPTION
**Pull request by paulelie**
Ref: https://github.com/ionic-team/capacitor/issues/337

Fixed with adding `modalPresentationStyle` to `overFullScreen` property on storyboard

### CODE REVIEW

**Comment by mlynch** [comment]
@paulelie awesome, thanks so much for the PR!

**Comment by A-Industry** [comment]
Also running into this issue now
screen shot 2018-08-28 at 15 17 44

**Comment by AVatch** [comment]
Just to point out this white spacing issue disappears if orientation is changed or the status bar visibility is toggled.

That being said perhaps there is some constraint being set to the bottom safe area region on iPhones which does not initialize properly?

**Comment by paulelie** [comment]
Still working on it (when i have time); BTW could you try this snippet on your app.component:

1. After your imports:
```
declare const document:any;
```
2. In constructor :
```
constructor(platform: Platform){
platform.ready().then(()=>{
 document.querySelector('meta[name=viewport]').setAttribute('content', 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no');
})
}
```

**Comment by A-Industry** [comment]
Yes that helps :) But now the application header is not shown under the the statusbar. So it is has a grey/white background
screen shot 2018-08-28 at 15 48 03

**Comment by A-Industry** [comment]
I found an easy fix: I removed the app.component.ts fix and just added
`html[mode="ios"] {
  height: 100vh;
}`

to global.scss. Now it works as expected.

**Comment by Devleaf-IT** [comment]
I'm still having this issue, even with the above mentioned fixes. Does anyone know the status of this problem? Thank you!

**Comment by paulelie** [comment]
> I'm still having this issue, even with the above mentioned fixes. Does anyone know the status of this problem? Thank you!

Hello,
Sorry for late answer.. It partially fix it, because if you use an native plugin, it will break your layout again... I've plan to check out/investigate more deeply on my extra-time.. will post on this feed if i found something
BTW thanks @A-Industry for your trick ;)

**Comment by jcesarmobile** [comment]
should be fixed by https://github.com/ionic-team/capacitor/pull/856, so going to close

**Pull request closed without merging**
