### PR TITLE
Feat/photo save video to album (ios)

### PR DESCRIPTION
**Pull request by stewwan**

### CODE REVIEW

**Comment by stewwan** [comment]
sample app can be found here

https://github.com/stewwan/capacitor-photos-save-video

**Comment by MarkChrisLevy** [comment]
@stewwan I think, that it should not be included in Capacitor repo, as this is additional plugin, not used by all apps. BTW I made a plugin, that does the same (only images for now, but both ios and android supported) - https://github.com/co-mmons/capacitor-multimedia-library-plugin

**Comment by stewwan** [comment]
@MarkChrisLevy let's see what core team think. for me it makes totally sense since capacitor already has the Photo api built in, otherwise I would publish it from my own npm.

@jcesarmobile should review soon

**Comment by MarkChrisLevy** [comment]
@stewwan My bad, I didn't see Photos plugin, as it is not presented in the docs site... In that case I will make a PR with Android implementation :-)

**Comment by stewwan** [comment]
I ended up by doing a separate plugin for this.

https://github.com/stewwan/capacitor-media

**Pull request closed without merging**
