### PR TITLE
fix(cli): Allow to filter incompatible plugins per platform

### PR DESCRIPTION
**Pull request by jcesarmobile**
and add `cordova-plugin-googlemaps` as iOS incompatible only.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
abusing?

**Comment by jcesarmobile** [comment]
???
The plugin causes build failures on iOS, this allow people to still use it on Android

**Comment by wf9a5m75** [comment]
At least, you should list here, not just blocking secretly.
Nobody can not found until inspecting the code.

https://github.com/ionic-team/capacitor/blob/29087ec682c29184efa2d25037cdf542d7c259ac/site/docs-md/cordova/known-incompatible-plugins.md

**Comment by jcesarmobile** [comment]
When you run update command it tells you the plugin is incompatible, so it’s not a secret. But yeah, I’ll add it to the list

**Comment by jcesarmobile** [comment]
documented on https://github.com/ionic-team/capacitor/pull/2072

**Pull request merged**
