### PR TITLE
fix(iOS): Separate cookies by `; ` rather than `;` when accessing through `document.cookie`

### LINKED ISSUE #6308: bug: Capacitor Cookies - `document.cookie` not behaving as expected on iOS
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/ios: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

iOS

#### How it Manifests
I have an Ionic React application using [Auth0 React](https://github.com/auth0/auth0-react). I have successfully configured it so that user sessions persist when the user closes and relaunches the app. However, this is broken on Native iOS when Capacitor Cookies is enabled; after closing and relaunching the app the session is lost. Disabling Capacitor Cookies restores the correct behaviour.

Config:
```ts
// capacitor.config.ts
const config: CapacitorConfig = {
  ...,
  plugins: {
    CapacitorCookies: {
      enabled: true,
    },
  },
};
```
#### Technical Details
After some investigation I've uncovered an issue with the iOS monkeypatch of `document.cookie` with regards to how multiple cookies are joined into a single string. Specifically, multiple cookies are separated by `;` rather than `; `:

**Native iOS with Capacitor Cookies disabled**
image

**Native iOS with Capacitor Cookies enabled**
image

**Native Android with Capacitor Cookies enabled/disabled**
image

Note that Native Android with Capacitor Cookies both enabled and disabled, as well as Native iOS with Capacitor Cookies disabled, all separate cookies with a semicolon and space. However, when Capacitor Cookies is enabled, Native iOS separates cookies with only a semicolon. This results in critical errors parsing cookies.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#read_all_cookies_accessible_from_this_location):

> [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.4) mandates a single space after each semicolon, but some user agents may not abide by this.

Furthermore, popular libraries expect `; ` when parsing the `document.cookie` string:
- [js-cookie splits on `; `](https://github.com/js-cookie/js-cookie/blob/main/src/api.mjs#L57)
- [es-cookie splits on `; `](https://github.com/theodorejb/es-cookie/blob/master/src/es-cookie.ts#L45)

The relevant code in the iOS moneypatch appears to be [this line](https://github.com/ionic-team/capacitor/blob/57f8b39d7f4c5ee0e5e5cb316913e9450a81d22b/ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift#L91).

The Auth0 client library leverages `es-cookie` which is why this issue manifests for me. 

### Expected Behavior

The native iOS `document.cookie` (get) functionality should return cookies separated by `; ` (semicolon+space).

### Code Reproduction

No _(If would be helpful in this case let me know and I will create one)_

### Other Technical Details

`npm --version` output: `8.5.0`

`node --version` output: `v16.14.2`

`pod --version` output (iOS issues only):
```
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
1.11.3
```

### Additional Context

N/A

### PR DESCRIPTION
**Pull request by crhayes**
Fixes #6308

### CODE REVIEW

**Review by ItsChaceD — APPROVED** [review]

**Review by ItsChaceD — CHANGES_REQUESTED** [review]
~~We may need to take this suggestion: https://github.com/ionic-team/capacitor/issues/6308#issuecomment-1437161093~~ ~~Since this is technically a breaking change~~

**Review by ItsChaceD — APPROVED** [review]

**Comment by OskarLebuda** [comment]
@jcesarmobile  can you approve this PR? It's important for us to implement this plugin without any iOS problems

**Comment by crhayes** [comment]
@jcesarmobile Thoughts on this change? Is this something that would be considered with a minor release?

**Comment by crhayes** [comment]
I'm curious why my previous comment was marked as abuse? As far as I can tell it does not go against the contributing guidelines or code of conduct?

It's a little disconcerting considering I've taken the time to:
- investigate a problem and write a detailed report
- offered to push up a code reproduction if required
- pushed up a PR to fix the issue

Since I pushed up this PR I am advocating for it, which includes:
- Trying to determine if it's well received
- If not, how can concerns be addressed?
- Is this something that could make it into a minor release or would require a major release

If there's anything I can do to help please let me know.

**Review by giralte-ionic — APPROVED** [review]

**Comment by giralte-ionic** [comment]
@crhayes please merge with `main` for merge

**Comment by crhayes** [comment]
@giralte-ionic Done! Ready for merge, thanks!

Is this something you think would make it to the next patch/minor release, or would this be released with Capacitor 5?

**Comment by giralte-ionic** [comment]
@crhayes `main` is capacitor 5 to be. `4.x` is the cap4 branch. If you need this fix for 4 sooner than cap5 release (we're targeting beginning of April code gods willing) please submit a PR there and @ me and I'll make sure it gets merged.

**Pull request merged**
