### PR TITLE
Adding capacitor-unimag-swiper to plugins.md

### PR DESCRIPTION
**Pull request by mkw2000**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
You have added an "iOS only" note, but on the plugin readme it mentions Android events. 
It doesn't have Android code, but why document Android events then?

**Comment by mkw2000** [comment]
@jcesarmobile My blunder, I'm working on adding Android  , I removed that from readme for now.

**Comment by jcesarmobile** [comment]
If you are going to develop the android part too, why don't you wait until the plugin is ready?

**Comment by mkw2000** [comment]
Why did you add community plugins to the list with incomplete implementations if you are going to give me a hard time about this? I'm just trying to make this available to help others, I already got what I need from it.  Add it or don't it really doesn't make a difference to me.

**Comment by jcesarmobile** [comment]
I’m not giving you a hard time, we don’t accept everything people send, we review it first and sometimes request changes or don’t accept it.
The readme had problems and I told you. Then you fixed them, but you said you were working on the android part, so I told you to wait until it’s finished.

**Comment by mkw2000** [comment]
I'm curious why the creator of this plugin wasn't asked to wait - https://github.com/cleversolutions/zebraCapacitor

**Pull request closed without merging**
