### PR TITLE
Fixes WASM mimetype for static file server in a production-bundled iOS app

### PR DESCRIPTION
**Pull request by ggaabe**
WebAssembly imports don't work correctly on iOS production builds that must serve files within the app instead of over a dev server. This happens because iOS production builds use the `file://` protocol to retrieve build files from a static file server, which can strip the MIME type if the file extension isn't recognized by the static file server.

This issue doesn't happen on Android, or in dev iOS builds because both retrieve their build files from a localhost server, which provides the correct MIME type.

This fix defines the WASM file extension for the static file server within the iOS app.

This fix may resolve the WASM MIME type issues listed here:
https://github.com/ionic-team/capacitor/issues/774
https://github.com/ionic-team/capacitor/issues/1864
https://github.com/ionic-team/capacitor/issues/4444

**Minimum reproduction:**

1. Install npm package `@emurgo/cardano-serialization-lib-browser`
2. Attempt to import it in a packaged production iOS build (not hosted from a dev server): 
```ts 
await (
      await import('@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib')
).default
````
3. The app will throw an error: `Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'`

### CODE REVIEW

**Comment by iamcco** [comment]
Any update ?

**Comment by ggaabe** [comment]
@iamcco Not sure how long it'll take before / if this gets reviewed but if you add the changes I made here to your own info.plist the issue will be resolved.

**Comment by iamcco** [comment]
> @iamcco Not sure how long it'll take before / if this gets reviewed but if you add the changes I made here to your own info.plist the issue will be resolved.

Thanks, it works!

**Comment by Janaka-Steph** [comment]
Thank you so much, it works!

**Comment by mudlee** [comment]
I can confirm that these added lines solve my wasm issue as well.

**Review by markemer — APPROVED** [review]
This seems reasonable - I don't have a lot of WASM to test with but now that we have the Cap5 WASM fix, this seems like a good idea.

**Comment by jcesarmobile** [comment]
This is a change in the iOS app template, so if this gets merged it would be included in every capacitor app created after the PR gets merged, even if not using WASM. Most users don’t use WASM, so I don’t think this should be part of every app, in any case we should document that this might be needed for using WASM, not even sure if it’s needed for most WASM users as I’ve used WASM in the past without doing this change. 
If something broke since last time I tested WASM, then we should try to fix it from the code that returns the mime type, not from the template.
Can you provide a sample app that reproduces the issue?

**Comment by ggaabe** [comment]
I provided minimum conditions needed to reproduce with a specific WASM NPM package installation and import to test with that would trigger the issue.

This issue only affects iOS users on production-packaged builds.

I no longer work at the job where this issue had occurred and my fix was needed so I probably will not also spend time building out a template app to demonstrate reproduction. But I know this is an issue that has affected other WASM users with capacitor and that the fix works.

**Comment by markemer** [comment]
I don't know how we handle `file://` urls in the app - but this is a pretty easy way to support wasm from the filesystem or remote file servers. I'm not sure of the harm of adding it for people that don't need it, but if we wanted to add it using the CLI or further refine the WASM code that could work too. @ItsChaceD had some WASM fixes, but I think they were for HTTP delivered assets.

**Comment by arunrdd** [comment]
Sharing my experience in setting up [sql.js](https://sql.js.org/) with capacitor, which worked nicely when the changes proposed above are made to the `Info.plist` file.

I used `vite-plugin-static-copy` to copy the wasm file to the build folder using following configuration:
```
import { defineConfig } from 'vite';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
	plugins: [
		viteStaticCopy({
			targets: [{
				src: 'node_modules/sql.js/dist/sql-wasm.wasm',
				dest: 'wasm-files'
			}]
		})
	]
});
```

When the app tried to access `${window.location.origin}/wasm-files/sql-wasm.wasm`, it received a wrong response MIME type `application/octet-stream`. I can confirm now that this works in production iOS builds. Thank you @ggaabe for the fix!

**Pull request closed without merging**
