### PR TITLE
CLI: `npx cap update android` generates invalid paths on windows

### PR DESCRIPTION
**Pull request by moberwasserlechner**
Description of the problem:
I'm currently upgrading to Capacitor 1.0.0 and after I run
```
npx cap sync android
```
under Windows 10 my `settings.gradle` once again contains backslashes which are not allowed in Gradle/Java as directory separators. I think this happend after #867 but was fixed and just reappeared.

Here's my diff.

```
+++ b/android/capacitor.settings.gradle
@@ -3,10 +3,10 @@ include ':capacitor-android'
 project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

 include ':byteowls-capacitor-filesharer'
-project(':byteowls-capacitor-filesharer').projectDir = new File('../node_modules/@byteowls/capacitor-filesharer/android/@byteowls/capacitor-filesharer')
+project(':byteowls-capacitor-filesharer').projectDir = new File('../node_modules/@byteowls/capacitor-filesharer/android\@byteowls\capacitor-filesharer')

 include ':byteowls-capacitor-oauth2'
-project(':byteowls-capacitor-oauth2').projectDir = new File('../node_modules/@byteowls/capacitor-oauth2/android/@byteowls/capacitor-oauth2')
+project(':byteowls-capacitor-oauth2').projectDir = new File('../node_modules/@byteowls/capacitor-oauth2/android\@byteowls\capacitor-oauth2')

 include ':byteowls-capacitor-sms'
-project(':byteowls-capacitor-sms').projectDir = new File('../node_modules/@byteowls/capacitor-sms/android/@byteowls/capacitor-sms')
+project(':byteowls-capacitor-sms').projectDir = new File('../node_modules/@byteowls/capacitor-sms/android\@byteowls\capacitor-sms')
```

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version: 1.0.0
node version: v10.15.3
npm version: 6.9.0
CocoaPods version: not applicable (windows)

Steps to reproduce:
run `npx cap sync android` on windows on a project with capacitor plugins

### CODE REVIEW

**Comment by jcesarmobile** [comment]
We changed the plugin structure and looks like I broke this when adding the mappings for the old structure plugins.
I've sent a [simpler PR](https://github.com/ionic-team/capacitor/pull/1692) that fix it where I broke it and that should be futureproff in case path is used elsewhere, so going to close this one.

But thanks for your contributions!

**Comment by jcesarmobile** [comment]
BTW, I liked the `convertToJavaPath` function, maybe you can add it to utils (or some other file), export it and replace all the `.replace(/\\/g, '/');` with it.

**Comment by moberwasserlechner** [comment]
@jcesarmobile sure will do that later today. 

You mentioned changes in the plugin structure. Could you point me to the new structure. I would be very interested to upgrade my own plugins to the new plugin structure. 

thx

**Comment by jcesarmobile** [comment]
Mostly removed unneeded subfolders, you can check the changes in https://github.com/ionic-team/capacitor/commit/92daba13fdf04bcddc79a32098bd13d79b5589a7#diff-bdea542b89e1ff9a9edf123d45498be0, and a few other changes if you check the plugin-template folder history https://github.com/ionic-team/capacitor/commits/master/plugin-template,  but best way to check is probably creating a new sample project and compare with one of your existing plugins.

**Pull request closed without merging**
