### PR TITLE
fix: move `public` into iOS target directory

### PR DESCRIPTION
**Pull request by dwieeb**
The `public` directory, which contains generated web assets, should exist alongside the generated `capacitor.config.json` within the iOS target directory, not the Xcode workspace directory.

TODO:
- [ ] Add migration steps to upgrade guide.
- [x] Add a check for old pbxproj and link to upgrade guide.
- [ ] Update [these docs](https://capacitorjs.com/docs/v3/ios/configuration#renaming-your-app)

### CODE REVIEW

**Review by jcesarmobile — APPROVED** [review]
looks good

the .gitignore change for existing apps should be documented

also the native iOS project change, I find this one more problematic and easier to miss and can lead to a lot of users not knowing why their file changes don't get updated after the migration

should the CLI remove the existing `ios/app/public` folder? or should also be documented that users need to remove it?

**Comment by dwieeb** [comment]
The CLI should probably continue to support `ios/app/public`, warning the user during every `sync` to migrate with a link to the migration guide. When they delete the folder we can assume they made the project changes and start writing to the new location. Will that work?

**Comment by jcesarmobile** [comment]
since the public folder is gitignored, there can be the case that an user downloads the project and the folder is not there so the CLI thinks the migration was done, but it wasn't

maybe make the CLI check the `project.pbxproj` to see if the `path = public; sourceTree = SOURCE_ROOT;` was updated to `path = public; sourceTree = "<group>";` and if not, copy to the old location?

**Comment by dwieeb** [comment]
Good point.

> maybe make the CLI check the `project.pbxproj`

Yeah, should be possible. 👍

**Review by ikeith — APPROVED** [review]

**Pull request merged**
