### PR TITLE
feat(core): expose `methodName` via `CAPPluginCall`

### PR DESCRIPTION
**Pull request by robingenz**
Close https://github.com/ionic-team/capacitor/issues/7476

### CODE REVIEW

**Comment by markemer** [comment]
Yeah - so this is a pretty breaking change - we'd need to have both versions of the plugin call or do this in a more subtle way.

**Comment by robingenz** [comment]
Why is it a breaking change? Who else creates instances of `CAPPluginCall`? Or am I missing something obvious?

**Comment by markemer** [comment]
> Why is it a breaking change? Who else creates instances of `CAPPluginCall`? Or am I missing something obvious?

You may be right actually - I think I was looking at this a bit early in the morning here - let me double check, I think I was been confusing it with a different function.

**Comment by markemer** [comment]
Yeah, these are available publicly - I don't think anyone is using them - but leaving the old version with a deprecation tag makes some sense - and we can just set it to blank or "unknown" in case someone does use it.

**Comment by robingenz** [comment]
> Edit: I can add that real fast if you don't mind me messing with your branch.

Yes, feel free to make the changes. 🙌

**Comment by robingenz** [comment]
@markemer I have added the old version with a deprecation tag again. Let me know if you need any other changes.

**Review by markemer — APPROVED** [review]

**Review by Steven0351 — APPROVED** [review]
lgtm

**Review by andredestro — APPROVED** [review]

**Pull request merged**
