### PR TITLE
fix(android): resolve issue with activity result API registration for fragments

### PR DESCRIPTION
**Pull request by carlpoole**
Prerequisite: #4405

### CODE REVIEW

**Review by jcesarmobile — COMMENTED** [review]
I think we could have a helper on Bridge class that help us get the activity or fragment, something like this:

```
    public ActivityResultCaller getResultCaller() {
        if (this.fragment != null) {
            return this.fragment;
        } else {
            return this.context;
        }
    }
```

This way we can avoid having the fragment null check and having to duplicate the code that is called once with `getFragment` and another one with `getActivity when `registerForActivityResult` is used

**Comment by carlpoole** [comment]
> I think we could have a helper on Bridge class that help us get the activity or fragment that is going to register for result

Thanks for the idea, this does make it cleaner. Take a look what I added

**Comment by jcesarmobile** [comment]
Looks good, can you use it in BridgeWebChromeClient too?

**Review by thomasvidas — APPROVED** [review]

**Review by jcesarmobile — APPROVED** [review]
looks good!

**Pull request merged**
