### PR TITLE
Extra iOS and Android configuration fields to add Capacitor to existing native apps

### PR DESCRIPTION
**Pull request by Kniniurb**
Some minor changes to config.ts and ios/update.ts to introduce more flexibility in how the iOS and Android projects are named and organised. Purpose: To add Capacitor to existing native projects.

### CODE REVIEW

**Comment by Squixx** [comment]
Anyone willing to review this?

**Review by riderx — APPROVED** [review]

**Comment by Kniniurb** [comment]
Hi Martin,

Thank you for the approval. How can I merge this with the main branch as I
do not have write access and how can I perform the checks (see picture)?
[image: Screenshot 2022-03-04 at 14.00.50.png]

Best regards,

Peter Bruinink

Op vr 4 mrt. 2022 om 12:45 schreef Martin DONADIEU ***@***.***

**Comment by riderx** [comment]
You can't, it's still necessary for a team member to review it :/

**Comment by Kniniurb** [comment]
Thanks!! Any idea how to get a team member to review it?

Op za 5 mrt. 2022 om 05:45 schreef Martin DONADIEU ***@***.***

**Comment by giralte-ionic** [comment]
@Kniniurb this feature seems very similar to our [Portals](https://github.com/ionic-team/ionic-portals) project - will this suit your needs or do you have a different use-case?

**Comment by giralte-ionic** [comment]
Closing after a year of inactivity

**Comment by riderx** [comment]
@giralte-ionic portal is only available for Paid customers, the solution of @Kniniurb was good for open-source side

**Comment by riderx** [comment]
the onboarding requires to register to ionic, on the website it say it's paid and contact the sales team.
In the doc it's say the token is free.
Seems portal are not as Open as Capacitor, that why the PR is still valid for me.

**Pull request closed without merging**
