### PR TITLE
fix(cli): avoid npm gitignore rename on new plugins

### PR DESCRIPTION
**Pull request by jcesarmobile**
npm renames .gitignore files to .npmignore files. That makes the plugin generator lose the .gitignore file the template has (only happen when running from npm installed package, not present if using locally linked/installed CLI)

This PR renames the .gitignore to gitignore and the CLI on plugin generation renames the file back to .gitignore

closes https://github.com/ionic-team/capacitor/issues/1980

### CODE REVIEW

**Comment by dwieeb** [comment]
I noticed this as well. Would it make sense to create an archive of each CLI asset directory and then unpack it?

**Comment by jcesarmobile** [comment]
Can this renaming cause problems to prefer the archive and unpack?
We do this renaming at the moment for android-template and ios-template too, so if we do the pack/unpack those should work the same way.

**Comment by dwieeb** [comment]
I just personally think renaming/moving files from an original template adds complexity. We might want to reevaluate this for Capacitor 3.

We can ship this quick, though.

**Comment by dwieeb** [comment]
See https://github.com/ionic-team/capacitor/pull/3292.

**Pull request closed without merging**
