### PR TITLE
fix "TypeError: requiredElementsArray is not iterable" when undefined

### PR DESCRIPTION
**Pull request by fangruhua**
[fatal] TypeError: requiredElementsArray is not iterable
    at doesContainElements (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:362:51)
    at doesContainElements (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:384:45)
    at doesContainElements (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:384:45)
    at doesContainElements (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:384:45)
    at doesContainElements (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:384:45)
    at logiOSPlist (/path/to/src-capacitor/node_modules/@capacitor/cli/dist/cordova.js:398:22)

### CODE REVIEW

**Comment by corxit** [comment]
In my case, I found this problem was caused by such item inside iOS info.plist. Bool type item  parsed as object which has no children `{ name: 'true' }`
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

Unexpected code block stack trace: 
```
 if (existingElement.name === requiredElement.name) {
      if ((requiredElement.children !== undefined) ===
          (existingElement.children !== undefined)) { /* 👈 this condition will cause method doesContainElements() throw error */
          if (doesContainElements(requiredElement.children, existingElement.children)) {
              foundMatch = true;
              break;
          }
      }
  }
```

**Comment by jcesarmobile** [comment]
can you provide an app that reproduces the issue?
I've tried adding this to another app we used to a similar issue but still can't reproduce
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

**Comment by fangruhua** [comment]
Here is the content of my Info.plist file,

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDevelopmentRegion</key>
<string>$(DEVELOPMENT_LANGUAGE)</string>
<key>CFBundleDisplayName</key>
<string>MyAppName</string>
<key>CFBundleExecutable</key>
<string>$(EXECUTABLE_NAME)</string>
<key>CFBundleIdentifier</key>
<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundleName</key>
<string>$(PRODUCT_NAME)</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleShortVersionString</key>
<string>2.5.1</string>
<key>CFBundleURLTypes</key>
<array>
<dict>
<key>CFBundleURLName</key>
<string>weixin</string>
<key>CFBundleURLSchemes</key>
<array>
<string>secret</string>
</array>
</dict>
</array>
<key>CFBundleVersion</key>
<string>1</string>
<key>ITSAppUsesNonExemptEncryption</key>
<false/>
<key>LSApplicationQueriesSchemes</key>
<array>
<string>weixin</string>
<string>wechat</string>
<string>weixinULAPI</string>
</array>
<key>LSRequiresIPhoneOS</key>
<true/>
<key>NSAllowsArbitraryLoads</key>
<true/>
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>
<key>NSCameraUsageDescription</key>
<string></string>
<key>NSPhotoLibraryUsageDescription</key>
<string></string>
<key>UIBackgroundModes</key>
<array>
<string>remote-notification</string>
</array>
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
<key>UIMainStoryboardFile</key>
<string>Main</string>
<key>UIRequiredDeviceCapabilities</key>
<array>
<string>armv7</string>
<string>arm64</string>
<string>wifi</string>
</array>
<key>UIRequiresFullScreen</key>
<false/>
<key>UIStatusBarHidden</key>
<true/>
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleDarkContent</string>
<key>UISupportedInterfaceOrientations</key>
<array>
<string>UIInterfaceOrientationPortrait</string>
</array>
<key>UISupportedInterfaceOrientations~ipad</key>
<array>
<string>UIInterfaceOrientationLandscapeLeft</string>
<string>UIInterfaceOrientationLandscapeRight</string>
<string>UIInterfaceOrientationPortrait</string>
<string>UIInterfaceOrientationPortraitUpsideDown</string>
</array>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
</dict>
</plist>


The capacitor dependencies in my src-capacitor/package.json file are:
***@***.***/android": "^5.2.2",
***@***.***/app": "^5.0.6",
***@***.***/cli": "^5.2.2",
***@***.***/core": "^5.2.2",
***@***.***/ios": "^5.2.2",


Hope information above would be helpful in reproducing this issue.


On Wed, Jul 26, 2023, at 22:28, jcesarmobile wrote:
> 
> 
> 
> 
> can you provide an app that reproduces the issue?
> I've tried adding this to another app we used to a similar issue but still can't reproduce
> 
> 
> `<key>NSAppTransportSecurity</key>
> <dict>
>     <key>NSAllowsArbitraryLoads</key>
>     <true/>
> </dict>
`

**Comment by jcesarmobile** [comment]
it's not helpful, can you please provide a full app?
the problem is most likely related to some cordova plugin you have installed

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Pull request closed without merging**
