### PR TITLE
[Android] Moved geolocation plugin to Fused Location Provider

### PR DESCRIPTION
**Pull request by exelban**
Related to #379 
Moved from standard android geolocation API to Fused Location Provider.

With old standard API, I have many problems with position updates.
Sometimes API returns position from many hours ago. And I can't make a force update. 

This version of plugin work for a few months on our app. And during this time don't have any problems with GPS.

I tried to make API the same as with standard Android API. So, I think the plugin will be backward compatible.

### CODE REVIEW

**Comment by aheiz** [comment]
Why is this closed? Do we have to use the community plugin "@johannesnormannjensen/capacitor-fused-location" to use fused location?

**Comment by exelban** [comment]
@aheiz I rewrite geolocation plugin to use in my project. And I create a PR for this. But there was no feedback from maintainers for a long time. And I closed this PR.

**Comment by shuhikari** [comment]
@exelban Did you manage to get the geolocation running ?

**Comment by exelban** [comment]
> @exelban Did you manage to get the geolocation working ?

Yes

**Comment by shc261392** [comment]
@exelban Would you like to share the rewritten plugin? I've been experiencing some problems with the original geolocation plugin too and it would be great if I could use your solution.

**Comment by exelban** [comment]
@shc261392 yeap. I will share the code in the next few days

**Comment by exelban** [comment]
@shc261392 @shuhikari [link](https://gist.github.com/exelban/67020d6f1de0dc9edb93056bec83e493) to code and a short description of how to wap it with existing Geolocation plugin.

**Comment by jcesarmobile** [comment]
capacitor 2.0.0-beta.1 uses fused location provider, you can install it like this: `npm intall @capacitor/android@next`

**Pull request closed without merging**
