### PR TITLE
feat(): Add recursive option for rmdir

### PR DESCRIPTION
**Pull request by 27pchrisl**
Filesystem.rmdir has different behaviour on iOS to other platforms (deletes recursively on iOS, does not on other platforms). This addresses the inconsistency by making all platforms delete recursively.

### CODE REVIEW

**Comment by 27pchrisl** [comment]
Hi, I think that it should be possible to command the native code to do the rmdir on your behalf (either with or without an option), as the performance better than the JS code doing it over the bridge. That was my motivation for making that behaviour common across platforms for our app.

**Comment by 27pchrisl** [comment]
Behaviour updated, added 'recursive' option that defaults to false

**Comment by 27pchrisl** [comment]
Tests seem to be failing due to an internal CircleCI error

**Comment by jcesarmobile** [comment]
I've merged your other PR and not this one have conflicts, can you fix them?

Hopefully tests will pass this time, they sometimes hang for no reason.

**Comment by 27pchrisl** [comment]
Conflicts fixed

**Pull request merged**
