### PR TITLE
Filesystem plugin for chrome browsers added

### PR DESCRIPTION
**Pull request by Beutlin**
Here is a version for the browser's fileapi plugin.

### CODE REVIEW

**Comment by mlynch** [comment]
Wow, awesome! Does this only work in Chrome? I forget what happened with the FS API but last I checked it wasn't going to go anywhere. There was some talk of a new API?

**Comment by henrysachs** [comment]
Hey, 

I tried to use your implementation but when I try to write a file i get the error: ``` QuotaExceededError: The operation failed because it would cause the application to exceed its storage quota.``` 
any ideas?

**Comment by henrysachs** [comment]
This is the code i used for this:
```javascript
import { Component, OnInit } from '@angular/core';
import {
  Plugins,
  FilesystemDirectory,
  FilesystemEncoding
} from '@capacitor/core';

const { Filesystem } = Plugins;
@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss']
})
export class HomePage implements OnInit {
  public event = {
    month: '1990-02-19',
    timeStarts: '07:43',
    timeEnds: '1990-02-20'
  };
  ngOnInit() {
      this.fileWrite();
  }

  fileWrite() {
    navigator.storage.estimate().then(estimate => {
      console.log(estimate);
    });
    Filesystem.stat({ directory: FilesystemDirectory.Data, path: './' }).then(
      data => {
        console.log(data);
      }
    );
    try {
      const ret = Filesystem.mkdir({
        path: 'secrets',
        directory: FilesystemDirectory.Data,
        createIntermediateDirectories: false // like mkdir -p
      });
    } catch (e) {
      console.error('Unable to make directory', e);
    }
    Filesystem.writeFile({
      path: 'text.txt',
      data: 'This is a test',
      directory: FilesystemDirectory.Data,
      encoding: FilesystemEncoding.UTF8
    }).catch();
  }
}

```

**Comment by jcesarmobile** [comment]
Well, Share plugin only works on Android's Chrome browser, so it will break in any desktop browser or mobile browser different from Chrome. Once other vendors add `navigator.share` it should just work, but for now it only works in Android's Chrome.

Didn't review this PR, but if it handles cases where it's not available returning some error or rejecting the promise I think we can merge it, and hope other vendors also implement it, or adjust the plugin in the future for other vendor implementations (if they implement it)

**Comment by henrysachs** [comment]
I would love to have this merged just for the developement process. But i had a hard time getting it to work.

**Comment by Beutlin** [comment]
@henrysachs 
Thank you for your feedback. I've improved my code. Now the write permission is asked per default.

**Comment by henrysachs** [comment]
Cool! Thank you @Beutlin! 🎉

**Comment by Beutlin** [comment]
I've implemented a new filesystem api based on IndexedDB: #1038
Therefore I will withdraw this Pull Request.

**Pull request closed without merging**
