### PR TITLE
fix(android): Release the call after reject/resolve

### PR DESCRIPTION
**Pull request by jcesarmobile**
Capacitor calls are being saved when an intent is being launched and then released after the intent returns a result, but before the plugin returns the result, and in cases where there are multiple intents launched by the same plugin call it ends up creating null pointer exceptions in some cases where the call was released sooner than expected and needed later.

This PR removes the early releases of the calls and put it where the call actually rejects or resolves to the JS side.

closes https://github.com/ionic-team/capacitor/issues/4307

### CODE REVIEW

**Comment by carlpoole** [comment]
Will this not regress this fix if the call is saved again before it is resolved? https://github.com/ionic-team/capacitor/pull/4281

**Comment by jcesarmobile** [comment]
I tried and doesn't look like it, if the call is saved again, since it's the same call, with same id, and savedCalls is a `Map`, it should just save the same call on the `Map` with no side effects as Maps don't allow duplicate keys.

**Comment by carlpoole** [comment]
I understand this now. I do like this a lot better. So basically the life of the call lasts until it is resolved/rejected (aka finished) and if you want the call to last past that, use the keepAlive setting. And it works because the call isn't resolved until the native work has been completed - which can last through multiple intents.

**Review by carlpoole — APPROVED** [review]
Tested and seems to work great

**Pull request merged**
