### PR TITLE
fix(cli): avoid srcFiles is not iterable on kotlinNeededCheck

### PR DESCRIPTION
**Pull request by jcesarmobile**
if the cordova plugin doesn't have any source files (i.e. es6-promise-plugin)

### CODE REVIEW

**Review by IT-MikeS — APPROVED** [review]

**Comment by daniel-zero** [comment]
Thanks for the quick fix. Would it be possible to release it as a hotfix update soon?

**Comment by tigohenryschultz** [comment]
I created this ticket for this issue: https://github.com/ionic-team/capacitor/issues/5482

I reverted to 3.4.1 and it fixed my issues.

**Comment by UTSOURCE** [comment]
me to

**Comment by Xelit3** [comment]
Seems that the problem is still happening with 3.4.3

I also reverted to a previous version, in my case 3.3.3 and it worked

**Comment by jcesarmobile** [comment]
If it's still happening in 3.4.3, can you create a new issue and provide more information?

**Pull request merged**
