### PR TITLE
fix(cli): apkName for multi-dimensional flavors

### PR DESCRIPTION
**Pull request by julienfdev**
This PR fixes the apkName problem with multi dimensional flavors on Android.

Discussed here > #6703

### CODE REVIEW

**Review by markemer — CHANGES_REQUESTED** [review]
Can you run `npm run fmt` on this?

**Comment by julienfdev** [comment]
Just did, changed my 3 edited files, sorry for the oversight !

**Review by giralte-ionic — APPROVED** [review]

**Comment by Cynthion** [comment]
Why is this PR not merged? I could use this feature :-)

**Comment by luisbytes** [comment]
I am having this problem, I hope they merge it soon

**Comment by luisbytes** [comment]
@giralte-ionic Hello, will this fix be published in Capacitor v5?

**Comment by luisbytes** [comment]
@markemer Hello, will support be added for the build command?

**Pull request merged**
