### PR TITLE
docs: Add new community tutorials

### PR DESCRIPTION
**Pull request by akhromieiev**
Add new tutorials from my blog "akhromieiev.com"

### CODE REVIEW

**Comment by dotNetkow** [comment]
hi @akhromieiev - were you able to make the changes Julio mentioned above?

**Comment by akhromieiev** [comment]
Hi @dotNetkow! Sure! I will update them in the near future.

**Comment by akhromieiev** [comment]
@jcesarmobile 
Hi! I updated all tutorials to Capacitor 1.1 and Ionic 4.4.0

**Comment by akhromieiev** [comment]
@jcesarmobile Hi! I see the article s not updated on site. Could you check the build, please?

**Pull request merged**
