### PR TITLE
fix(ios): set cors headers in asset handler for live reload

### PR DESCRIPTION
**Pull request by ItsChaceD**
Addresses: #4089

This PR sets CORS headers so local files can be fetched on iOS while using live reload.

### CODE REVIEW

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
The CORS header should only be added when using live reload, this code also adds it when not using live reload.

I don't think we have a method for checking if live reload is being used as `serverURL` is being set to `localURL` as default value if not set, so you'll have to compare if `localURL` and `serverURL` are different and only set it on the `WebViewAssetHandler` in that case. 
Which also means, `serverURL` in `WebViewAssetHandler` should be optional and `WebViewAssetHandler` would not change, but a new method for setting the `serverURL` should be added.

**Review by IT-MikeS — APPROVED** [review]

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
The headers are still being added for all requests, not just for live reload requests.

The server url is `capacitor://localhost` and the file url is `capacitor://localhost/_capacitor_file_/.../photo-xx.jpg`, so they are different and goes inside the if.
It should probably compare the schemes since the CORS errors appear when using different schemes. For that, it might be better to store the `serverUrl` as `URL` instead of as `String`

**Comment by markemer** [comment]
> The headers are still being added for all requests, not just for live reload requests.
> 
> The server url is `capacitor://localhost` and the file url is `capacitor://localhost/_capacitor_file_/.../photo-xx.jpg`, so they are different and goes inside the if. It should probably compare the schemes since the CORS errors appear when using different schemes. For that, it might be better to store the `serverUrl` as `URL` instead of as `String`

Since live reload is just a development feature anyway, could we wrap this in an `#if DEBUG`? That'd be safer anyway.

**Comment by jcesarmobile** [comment]
Well, not really, while I talk about "live reload", the CORS headers should also be added when using `server.url` for both live reload and for loading external sites.
While we don't officially recommend doing that, there are a lot of people doing it and the headers should be added for that case too, so shouldn't be done for debug builds only.

**Review by jcesarmobile — APPROVED** [review]

**Pull request merged**
