### PR TITLE
[WIP] Toast/Notification Plugin for Electron

### PR DESCRIPTION
**Pull request by IT-MikeS**
Electron exposes native notifications through the HTML5 Notification API, simple plugin for that.

Needs expanding.

### CODE REVIEW

**Comment by mlynch** [comment]
I love it, only concern is the expectations that this is a Toast UI component, rather than a notification. Might make more sense to keep this in a different Plugin?

Also, if we go the Toast UI route, we can use an Ionic web component (like we do the Camera), which would mean little UI work

**Comment by IT-MikeS** [comment]
Very true, maybe this is more of the Electron equivalent of `Push Notifications` as a local option and a wire up for a service too.

**Comment by mlynch** [comment]
Cool, how about this: re-implement this using the Ionic Toast component in Ionic 4: https://github.com/ionic-team/ionic/blob/master/core/src/components/toast/test/basic/index.html

This is the same approach we're taking for the Camera. For now, you can test by adding this script to the index file:

`<script src="https://unpkg.com/@ionic/core@0.1.5-2/dist/ionic.js"></script>`

**Comment by IT-MikeS** [comment]
Yeah I'll work on this over the next little bit

**Pull request closed without merging**
