### PR TITLE
Capturing keypresses in Android

### PR DESCRIPTION
**Pull request by JStumpp**
Closes https://github.com/ionic-team/capacitor/issues/371

### CODE REVIEW

**Comment by mlynch** [comment]
Thanks, can you explain a bit about what this does? Also `Webview` should be `WebView`

**Comment by mlynch** [comment]
Okay cool did some research. I'll merge after the rename to `CapacitorWebView`

**Comment by JStumpp** [comment]
CamelCase is fixed.

**Comment by mlynch** [comment]
Sweet, thanks!

**Comment by jcesarmobile** [comment]
This was causing some problems and had a few limitations, so we have changed it to use the default keyboard as the default option, but it's still possible to use the `BaseInputConnection` keyboard by using a preference in `capacitor.config.json`. You'll have to set it if you want to continue capturing keypresses.

See https://github.com/ionic-team/capacitor/pull/718 and https://github.com/ionic-team/capacitor/pull/717 for more information

**Comment by ArmorDarks** [comment]
Note that this might be related to newly appeared #757

**Pull request merged**
