### PR TITLE
Using official github android gitignore template

### PR DESCRIPTION
**Pull request by JStumpp**
Capacitor was missing important ignores:
https://github.com/github/gitignore/blob/master/Android.gitignore

### CODE REVIEW

**Comment by janpio** [comment]
Maybe add that source URL as a comment as well?

**Comment by JStumpp** [comment]
Good point, added!

**Comment by mlynch** [comment]
I assume with the recent fix to `gitignore` on platform add, this won't cause any breaking? We ship a `.iml` to maintain the project for fast import to Android Studio

**Comment by JStumpp** [comment]
Oh, you are shipping .iml, I did not realize that. Doesn't this create more problems than it solves?

**Comment by mlynch** [comment]
I don't think so. The Android mantra is to be IDE agnostic, but we're very much focusing on Android Studio, so I think that's the only sticking point. It makes the first import into Android studio seamless, and the `.iml` references are all local. Basically when you first run `npx cap open android` it Just Works, no import prompts, no errors, etc.

**Comment by JStumpp** [comment]
Ok, i had an issue with the gradle import that I had to click gradle sync twice. So maybe the .iml is ok for a seamless first import. But when working in a team checkin in .iml is usually not a good idea.

**Comment by mlynch** [comment]
yea makes sense, I don't think this would break that but needs testing

**Pull request merged**
