### PR TITLE
feat(splash): splash can be animated on android

### LINKED ISSUE #789: feat(splash/android): splash can be an animated drawable
I'd like to request the possibility to use an animated drawable as a splash screen.

We only need to add those three lines after the creation of the `Drawable` in `Slash.java`.
```
    if (splash instanceof Animatable) {
      ((Animatable) splash).start();
    }
```
I tested it and it works wonderfully! Ask me if you want a PR.

### PR DESCRIPTION
**Pull request by ptitjes**
Fixes #789.

### CODE REVIEW

**Comment by ptitjes** [comment]
For the record, here is what can be achieved with this PR:

Animated splash screen example

[Better quality video](http://ptitjes.free.fr/cabasvert/animated-splash-screen.mp4)

**Comment by ptitjes** [comment]
@mlynch Would you mind to review my harmless three-liner change ? :)

**Comment by hiepxanh** [comment]
wow, that pretty cool. I like it, please then can you make an tutorial about this. What is animating? image? gif ? or video?

**Comment by mlynch** [comment]
Awesome! Thanks for the PR

**Comment by hiepxanh** [comment]
ya, thank you for that information

**Comment by ptitjes** [comment]
@mlynch When do you think you'll make a release ?

**Pull request merged**
