### PR TITLE
fix(android): implement getDeliveredNotifications and removeDeliveredNotifications

### PR DESCRIPTION
**Pull request by p7g**
This PR implements the `PushNotifications` plugin `getDeliveredNotifications` and `removeDeliveredNotifications` methods.

The fields available on the objects returned by `getDeliveredNotifications` are a subset of those available on iOS, but otherwise the behaviour should be the same.

### CODE REVIEW

**Comment by trytuna** [comment]
This is 23 days old. Can we please merge that?

**Comment by jcesarmobile** [comment]
How I'm supposed to use the removeDeliveredNotifications? If I first use getDeliveredNotifications and pass the result to removeDeliveredNotifications, all the ids are 0, so doesn't remove the notifications.

For local notifications it works since we set the id, but it's confusing since the PR is about Push notifications

**Comment by p7g** [comment]
@jcesarmobile In my use-case I have a subclass of `FirebaseMessagingService` that sets the IDs of incoming notifications. I understand that not everyone will want to have this, but I think the problem of IDs  being 0 is a different issue than the one this PR addresses.

**Comment by jcesarmobile** [comment]
yeah, but on a regular Capacitor app this will happen, and I'm concerned about users complaining about it

**Comment by p7g** [comment]
I think that having these methods implemented is better than not.

I agree that users may encounter the issue you mentioned, but we can make a new issue to find out why the IDs of the notifications are 0.

**Pull request merged**
