### PR TITLE
feat(android): Enable AndroidX and use AndroidX dependencies

### PR DESCRIPTION
**Pull request by priyankpat**
Fixes Issue #1937

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Should be accepted anytime soon.

**Comment by PR1YANKPAT3L** [comment]
It's planned for [2.0.0 Milestone](https://github.com/ionic-team/capacitor/milestone/6) but I noticed it being a roadblock for lots of devs including myself. Having said that, it might make or break some of the projects depending on the plugins installed (Mainly Cordova plugins). I'd suggest forking and installing @capacitor/android locally as a temporary measure.

These are the Cordova plugins that I am currently using without any issue.

    cordova-background-geolocation (3.2.2)
    cordova-plugin-actionsheet (2.3.3)
    cordova-plugin-background-fetch (5.6.1)
    cordova-plugin-cocoalumberjack (0.0.4)
    cordova-plugin-dialogs (2.0.2)
    cordova-plugin-sim (1.3.3)
    cordova-sqlite-storage (3.4.0)
    cordova-support-google-services (1.3.1)
    phonegap-plugin-multidex (1.0.0)

**Comment by josh-m-sharpe** [comment]
I tested this by doing the following:
1) fork this branch locally
2) rebase against @capacitor v1.3.0 (released hours ago)
3) cd cli && npm build
4) cd core && npm build
5) in my project: npm link ~/path/to/capacitor/cli
6) in my project: npm link ~/path/to/capacitor/core
7) cap add android

I then opened android studio and ran Refactor -> Migrate to AndroidX.  That found some additional changes in android/app/build.gradle and android/app/src/main/AndroidManifest.xml

Here's that diff:

```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index eabb755..d634287 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -8,7 +8,7 @@ android {
         targetSdkVersion 28
         versionCode 1
         versionName "1.0"
-        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
+        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
     }
     buildTypes {
         release {
@@ -29,11 +29,11 @@ repositories {
 
 dependencies {
     implementation fileTree(include: ['*.jar'], dir: 'libs')
-    implementation 'com.android.support:appcompat-v7:28.0.0'
+    implementation 'androidx.appcompat:appcompat:1.0.0'
     implementation project(':capacitor-android')
     testImplementation 'junit:junit:4.12'
-    androidTestImplementation 'com.android.support.test:runner:1.0.2'
-    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
+    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
+    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
     implementation project(':capacitor-cordova-android-plugins')
 }
 
diff --git a/android/app/src/main/AndroidManifest.xml b/android/app/src/main/AndroidManifest.xml
index d416e80..af50629 100644
--- a/android/app/src/main/AndroidManifest.xml
+++ b/android/app/src/main/AndroidManifest.xml
@@ -32,7 +32,7 @@
         </activity>
 
         <provider
-            android:name="android.support.v4.content.FileProvider"
+            android:name="androidx.core.content.FileProvider"
             android:authorities="${applicationId}.fileprovider"
             android:exported="false"
             android:grantUriPermissions="true">
```

@PR1YANKPAT3L Should those deps also be updated with this PR?

**Comment by josh-m-sharpe** [comment]
This seems like something worth merging ASAP. I see it's on the list of milestone, but that list seems just a tad out of date.  @jcesarmobile could you add some insight there?

**Comment by jcesarmobile** [comment]
It’s in the 2.0.0 milestone because it’s a breaking change, so can’t be merged ASAP

**Comment by josh-m-sharpe** [comment]
@jcesarmobile no comment on the lack of milestone maintenance or insight into what's blocking this?  Please advise as to what needs to happen to get this released.

**Comment by jcesarmobile** [comment]
The only milestone I’m maintaining is 2.0.0 to track all the required breaking changes.
I didn’t create the other milestones so I can speak about them because I don’t know.

**Comment by PR1YANKPAT3L** [comment]
@josh-m-sharpe Thanks for the feedback. I am looking into it, will post updates/changes in a few hours.

**Comment by josh-m-sharpe** [comment]
@PR1YANKPAT3L nice update.  After running android studio's migration I no longer see a diff.

After clicking Run, I get this error though:
```
Compilation is not supported for following modules: capacitor-android, capacitor-fcm. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.
```

guessing I added capacitor-android incorrectly?  I've added it with `yarn add ~/capacitor/android`

**Comment by josh-m-sharpe** [comment]
@jcesarmobile What is the plan for 2.0.0?

**Comment by josh-m-sharpe** [comment]
@PR1YANKPAT3L following up on the previous comment... I'm definitely having trouble linking to a local version of `@capacitor/android`.  As of this writing, I'm installing it into my project like this:

```
git clone https://github.com/PR1YANKPAT3L/capacitor.git ~/capacitor
cd ~/capacitor/cli
npm install
npm run-script build
cd ~/capacitor/core
npm install
npm run-script build
cd ~/myProject
yarn add -D ../capacitor/cli
yarn add ../capacitor/core
yarn add ../capacitor/android
```


Then, when I build android, I get a whole slew of errors like the ones below, all referencing `node_modules/@capacitor/android` instead of my local version.

```
  symbol:   class CustomTabsServiceConnection
  location: package android.support.customtabs
/Users/vagrant/git/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java:12: error: cannot find symbol
import android.support.customtabs.CustomTabsSession;
```

and

```
/Users/vagrant/git/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/background/BackgroundTask.java:8: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
```

How are you installing/linking/whatever your local version s.t. you can use it in a project?

Thanks!

**Comment by PR1YANKPAT3L** [comment]
@josh-m-sharpe I recorded the process for easy install: [Link](http://recordit.co/2ul9Xux3GD)

Commands I used in sequence (Starting from your project root directory):
```
cd ..
git clone https://github.com/PR1YANKPAT3L/capacitor.git
cd capacitor
git checkout develop
cd ..
cd ./example-project
npm i ../capacitor/android --save
npx cap sync
npx cap open android
```

**Comment by PR1YANKPAT3L** [comment]
The last commit was meant for #2148 but it make sense to upgrade the versions along with androidx.

**Pull request merged**
