### PR TITLE
capacitor-567: Always print cordova plugins

### PR DESCRIPTION
**Pull request by wtrocki**
See #567

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@wtrocki thanks for the PR, but the problem really is that the "Found 0 Capacitor plugins for android:" appears twice.
I though the problem was that it was showing "Capacitor" instead of "Cordova" on the second one, but with your change now I get

> Found 0 Capacitor plugins for android:
> Found 0 Cordova plugins for android
> Found 0 Capacitor plugins for android:

So it still appears twice.

**Comment by jcesarmobile** [comment]
I've fixed it in https://github.com/ionic-team/capacitor/pull/576

But maybe it's a good thing to always print the Cordova plugins too, @mlynch what do you think?

I see you've made some changes since I reviewed, so you'll have to revert the changes back to just print Cordova plugins. But wait from Max confirmation if he likes to always print Cordova plugins or not

**Comment by wtrocki** [comment]
Let's close that then

**Comment by wtrocki** [comment]
Even after mentioned PR we are still calling print method twice. 
In my PR we just do that once so less input is printed. 
Let me know if you will want any further improvements. 

Bonus is that I learned cli architecture (it is impressive) so feel free to ping me on any future improvements :)

**Comment by jcesarmobile** [comment]
print method is called multiple times, but it's one for Capacitor plugins, other for Cordova plugins and another for incompatible Cordova plugins.
The problem was on the incompatible plugins print, as it had a length === 0 (no incompatible plugins found), it was going to the remaining else and printed as 0 Capacitor plugins, so by checking the type on the else we avoid that problem

**Pull request closed without merging**
