### PR TITLE
subscribe to & unsubscribe from a topic in Firebase Push Notification #1682

### PR DESCRIPTION
**Pull request by dibyendusaha**
Please review my code, and if possible allow to merge it to the base.
Subscribing and Unsubscribing from topic is now becoming an essential part of FCM, as with new API Endpoint if we need to send messages to multiple devices they are asking to create a topic as one of the options. So thought if we can have this directly in capacitor instead of using fcm-capacitor plugin from @stewwan 
Please let me know if there is any scope for improvement. @stewwan @dwlrathod

### CODE REVIEW

**Comment by stewwan** [comment]
back in 2018 when I approached @jcesarmobile in Slack about this feature he told me that it would fit better in a plugin. That's why I didn't it before,  otherwise I would have sent the PR.

**Comment by dibyendusaha** [comment]
> back in 2018 when I approached @jcesarmobile in Slack about this feature he told me that it would fit better in a plugin. That's why I didn't it before, otherwise I would have sent the PR.

I will suggest if you can also contribute and if we have this as a feature in capacitor

**Comment by dibyendusaha** [comment]
> Thanks for the PR, but we are not going to add a Firebase dependency to `@capacitor/ios`, that's why I told stewwan in the past that this was better in a separate plugin.
> So, we might add this for Android only, but you'll still need a separate plugin for iOS.

Thanks for the reply. So is it fine to have this feature only in android not in iOS? Should I remove all the methods that I have implemented for iOS?
Another question, why we do not want Firebase dependency for @capacitor/ios, will it is break if someone not using Firebase for their project?

**Comment by jcesarmobile** [comment]
on iOS they should be there, but return unimplemented error

dependencies increase the size of the apps, so adding firebase will increase the size for all user apps despite they don't use it

**Comment by jcesarmobile** [comment]
I got a notification about you requesting me to review, but you have not addressed the changes I proposed on my latest comment.

**Comment by stewwan** [comment]
This issue can be closed.

https://github.com/capacitor-community/fcm

**Comment by dwieeb** [comment]
Thanks for the PR @dibyendusaha! Unfortunately this functionality might not make sense in Capacitor core.

**Comment by dibyendusaha** [comment]
> Thanks for the PR @dibyendusaha! Unfortunately this functionality might not make sense in Capacitor core.

That's fine (Y)

**Pull request closed without merging**
