### PR TITLE
feat(ios): add useLog config #1431

### PR DESCRIPTION
**Pull request by stewwan**
@mlynch 
@jcesarmobile

### CODE REVIEW

**Comment by stewwan** [comment]
this PR provides a way to disable native logs #1431. you can control it on your `capacitor.config.json`

```json
{
  "useLog": false
}
```

**Comment by stewwan** [comment]
I can add the android version, just let me know if the api fits good.

**Comment by jcesarmobile** [comment]
I think this print should be a drop in replacement for regular print, so should look like

```
 public static func print(_ items: Any..., separator: String = " ", terminator: String = "\n") {
        if (self.useLog() as? Bool != false) {
            Swift.print(items, separator, terminator)
        }
    }
```
No need to have the `@objc` as print is Swift only (same for the other methods and class)

Not sure if we need this new `CAPLog` class, or if we can just put it inside the CAPBridge class, as it has a `modulePrint` function already, or move that one to the new CAPLog class.

Another thing, CAPConfig is no longer a singleton, so code should be changed.
First a static config should be declared
`public static let config = CAPConfig()`

And change the usage to
`let isProduction = config.getValue("production") as? Bool`
        
But I not sure about the `production` name of the preference, in my experience, people tend to think they are building a production app just by setting that value to true, so I would stick with showLogs, or hideLogs, or useLogs

Or maybe just don't make it configurable and hide all the logs when a release build is done with the DEBUG macro

```
#if DEBUG
  print(...)
#endif
```

@mlynch thoughts?

**Comment by stewwan** [comment]
drop in replacement looks awesome. thanks for the ideas.

from my work experience macros won't work. what if I wanted to check capacitor logs with my app in production mode.

**Comment by jcesarmobile** [comment]
As Max said we shouldn't show them by default, I suppose he means in production. 
So it should check both `isDevMode` method from CAPBridge and the configuration option in the `capacitor.config.json` to always show them in dev mode, but in production only if enabled with the preference.

**Pull request closed without merging**
