### PR TITLE
capacitor.config.json with templates

### PR DESCRIPTION
**Pull request by macdja38**
The basic idea is to allow for pulling in variables from the platforms configuration systems.

Both iOS and Android allow users to have different configurations for dev / release they may choose from when running a build, along with ways of managing that configuration with respect to source control.

This PR allows utilization of those values from the capacitor.config.json through the syntax $(variable_name). 

This could be part of the solution for: https://github.com/ionic-team/capacitor/issues/1478

And provides better configuration as asked for by me here: https://github.com/ionic-team/capacitor/issues/1741

Note that this PR only includes Android / iOS implementations, web / electron is not supported by this PR at this time.

Future improvements may include default values and non string types.

### CODE REVIEW

**Comment by jcesarmobile** [comment]
Can you explain how this works so I can test it?

Also, could you document it as part of the PR so everybody else can use it if merged?

**Comment by macdja38** [comment]
@jcesarmobile yup, will work on that next week. It needs to be implemented for web as well though, and I'm not really sure how that should look as web doesn't have a ubiquitous config system similar to android / iOS.

A brief overview of how it works is:

It replaces $(variable_name) values in the capacitor.config.json with variables by the same name in the platforms configuration.

So for example you can have in your capacitor.config.json
{
  "url": "$(url_var)"
}

then in your AndroidManifest.xml you can add a meta tag for url_var and have it change based on which build config you have when you run builds. Similarly on iOS you can use different builds to pull variables in from the project config. This allows stuff like using a different server url / navigable domain whitelist in production / development / staging without weird scripts to over-write the capacitor.config.json depending on what build stage you run.

**Comment by dwieeb** [comment]
@macdja38 Curious to hear your thoughts on an alternative implementation of this. Instead of using template syntax, we just allow JS config files. The Capacitor CLI would run the file to generate a config object which gets written into the native projets every time `cap sync` is run.

**Comment by macdja38** [comment]
> @macdja38 Curious to hear your thoughts on an alternative implementation of this. Instead of using template syntax, we just allow JS config files. The Capacitor CLI would run the file to generate a config object which gets written into the native projets every time `cap sync` is run. 

So long as the js config file has access to the environment from .env files I’m completely for it. 

This is actually similar to the solution I ended up going with except I wrote a tiny external (to the capacitor project) tool to execute the js config file to generate the capacitor.config.json.

I think it would be ideal to have access to the environments on each platform but the js file compiled at compile time would be nice as well.

**Comment by dwieeb** [comment]
@macdja38 Yeah it's just a file that will run with NodeJS so it will work with any config setup you want. Think webpack or rollup configs. I imagine the Capacitor CLI will provide some environment variables as well such as `CAPACITOR_PLATFORM`.

**Comment by dwieeb** [comment]
An alternative implementation will be in Capacitor 3, track https://github.com/ionic-team/capacitor/issues/3141 for details.

**Pull request closed without merging**
