### PR TITLE
fix(android): get application/x-www-form-urlencoded as string

### PR DESCRIPTION
**Pull request by jcesarmobile**
As far as I understand, when using `application/x-www-form-urlencoded` you send a string, so that's why the `body.toJSObject()` is crashing, because it's a string, not a JSObject.

The PR removes the whole `application/x-www-form-urlencoded` else and goes directly to the final else where it read the body as string.

If you think there might be bases where the `application/x-www-form-urlencoded` could be getting a `JSObject`, let me know and I'll change the code to catch the JSON exception and fallback to string in that case.

closes https://github.com/ionic-team/capacitor/issues/5996

### CODE REVIEW

**Review by theproducer — APPROVED** [review]
Looks good.  Tested this with one of the supplied reproductions and it worked.

As far as I know, I don't think you have to worry about JSObjects from a `x-www-form-urlencoded` response.  if that does happen, it should be on the caller to take the body response and parse as JSON.

**Review by IT-MikeS — APPROVED** [review]
`x-www-form-urlencoded` requests should always be sent with URL Query String formatted bodies. Users can accomplish this via a couple options:

- [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) in JS

- A custom mapping function that will convert your JS Object into query params:
```javascript
const bodyRequest = Object.keys(myJSObject).map(key => encodeURIComponent(key) + '=' + encodeURIComponent(myJSObject[key])).join('&');
```

In this case the Cap HTTP Plugin was accepting users sending JSON strings then auto converting them for users.

**Review by giralte-ionic — APPROVED** [review]

**Comment by emelampianakis** [comment]
Hello, it throws an exception for me:
JSONException
    org.json.JSONException: JSValue could not be coerced to JSObject.
        at com.getcapacitor.JSValue.toJSObject(JSValue.java: 39)
        at com.getcapacitor.plugin.util.CapacitorHttpUrlConnection.setRequestBody(CapacitorHttpUrlConnection.java: 194)
        at com.getcapacitor.plugin.util.HttpRequestHandler.request(HttpRequestHandler.java: 399)
        at com.getcapacitor.plugin.CapacitorHttp$1.run(CapacitorHttp.java: 34)
        at java.lang.Thread.run(Thread.java: 920)

Tried both URLSearchParams & custom mapping but still getting an exception.
What additional info can i give you to resolve the issue

**Comment by dnietodev** [comment]
Hello, when can we expect to have this fix with the next release of capacitor?

Thanks!

**Comment by jcesarmobile** [comment]
This was released in 4.6.2

**Pull request merged**
