### PR TITLE
feat(local-notifications): use app icon for default

### PR DESCRIPTION
**Pull request by mburger81**
waiting for custom icons we suggest to use at least default application icon before using ic_dialog_info

### CODE REVIEW

**Comment by jcesarmobile** [comment]
the problem with using app icon is, most of them are not valid notification icons and will just show a white circle or square

**Comment by mburger81** [comment]
On what is this depending? The icon it self, or the android platform? In our test case the app icon is simple better then the default info icon.

We could also do a PR for a custom small icon like cordova does. But we are not sure where should we should configure it? 
Do you want it As I a dedicated main property or in the extra property? For what is the extra property? There is no documentation about that. 
We are not native programmers so sorry if this this is a "stupid" question

**Comment by RoderickQiu** [comment]
> 
> 
> the problem with using app icon is, most of them are not valid notification icons and will just show a white circle or square

But on my own project, it shows the app's icon, if action bar icons are not set. (After using the code)

So it should be OK to merge that code?

**Comment by RoderickQiu** [comment]
However, I think request icon as a parameter seems to be better. 
But I'm not experienced in native coding...

**Pull request closed without merging**
