### PR TITLE
Update CAPLog.swift

### PR DESCRIPTION
**Pull request by 183959633**
Security issues, make code more robust

### CODE REVIEW

**Comment by ikeith** [comment]
Thanks for the PR! While it might be desirable to suppress logs in production, there are several issues to consider:

1) This would be a breaking change for existing applications where the log statements suddenly stop appearing as expected and no way to control it.
2) This change is only for the native iOS code. There is an existing issue about the number of console messages logged from javascript https://github.com/ionic-team/capacitor/issues/3723.
3) There is already an official way to turn off this logging: [the `hideLogs` flag in the configuration](https://capacitorjs.com/docs/reference/config).

**Comment by aparajita** [comment]
I have a WIP console replacement that addresses all of these issues by allowing the user to set a log level (among other enhancements).

**Comment by 183959633** [comment]
oh,which one, and how to use?

**Comment by aparajita** [comment]
@183959633 It's a work in progress, hopefully I'll get a chance to publish it next week.

**Comment by 183959633** [comment]
OK, thank you for your help. Congratulations!

**Comment by 183959633** [comment]
This link is invalid and cannot be found. Please send it again

**Comment by aparajita** [comment]
I didn't send a link, it isn't public yet.

**Comment by jcesarmobile** [comment]
There are multiple possible reasons for wanting logs in release builds, i.e. for release builds send to testers.

As ikeith said, it is already possible to turn it off with hideLogs configuration option, that allows the user to choose when to hide them instead of doing it automatically by release type.

**Pull request closed without merging**
