### PR TITLE
feat(cli): Add --forwardPorts option to Capacitor CLI

### PR DESCRIPTION
**Pull request by thomasvidas**
Exposes the `--forwardPorts` option from [native-run](https://github.com/ionic-team/native-run) to the Capacitor CLI. When an `npx cap run android --forwardPorts 8000:8000` is run, the following happens.

- A Capacitor Sync
- Device Boot & Connection
- `adb reverse tcp:${port} tcp:${port}`
- Install and run a debug APK

Opening as a Draft PR because
- changes may be needed in native-run to work properly
- maybe a `--live-reload` flag with the port in the config makes more sense?

### CODE REVIEW

**Comment by bastienlemaitre** [comment]
@thomasvidas  any new about this feature ?

**Comment by peitschie** [comment]
I'd be keen on this one landing too! Hit an issue today where manual port forwards are cleared by `native-run` under some circumstances, so having a flag like this would make the whole thing easier to deal with. I ended up needing to use the `wait-on` package to help work around things.

**Comment by markemer** [comment]
I've updated this to be merged to `main` and am looking at making sure it works.

**Review by theproducer — APPROVED** [review]

**Review by IT-MikeS — APPROVED** [review]

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
It's not working, the forwardPorts option is not being passed to the runCommand, should look like this:

```
async (platform, { scheme, flavor, list, target, sync, forwardPorts }) => {
            const { runCommand } = await import('./tasks/run');
            await runCommand(config, platform, {
              scheme,
              flavor,
              list,
              target,
              sync,
              forwardPorts
            });
          },
```

**Comment by markemer** [comment]
Huh, it worked for @theproducer - I'll take a look

**Comment by markemer** [comment]
> await runCommand

It does seem like that is missing.

**Review by IT-MikeS — APPROVED** [review]

**Review by giralte-ionic — APPROVED** [review]

**Review by jcesarmobile — APPROVED** [review]

**Pull request merged**
