### PR TITLE
Fix redirects on Android

### PR DESCRIPTION
**Pull request by tony-scio**
Based on https://github.com/ionic-team/capacitor/pull/4437

### CODE REVIEW

**Comment by jgoux** [comment]
> Based on #4437

Does it also address this : https://github.com/ionic-team/capacitor/pull/4437#issuecomment-815692337 ?

I'm hitting the same issue, after a redirect (for example an authentication flow), the capacitor bridge isn't injected anymore.

**Comment by tony-scio** [comment]
> > Based on #4437
> 
> Does it also address this : [#4437 (comment)](https://github.com/ionic-team/capacitor/pull/4437#issuecomment-815692337) ?
> 
> I'm hitting the same issue, after a redirect (for example an authentication flow), the capacitor bridge isn't injected anymore.

Unfortunately, it doesn't fix that. The bridge is still lost after redirect. But for my particular use case this was a strict improvement and unblocked us.

**Comment by tony-scio** [comment]
By the way, feel free to give this fork a try. I'll be keeping it up to date with the latest stable capacitor release until this is fixed upstream.

package.json::
`""@capacitor/android": "https://gitpkg.now.sh/tony-scio/capacitor/android?b6ccdb0e5bad540a7656a0d644231c96b00ae52b",`

**Review by riderx — APPROVED** [review]

**Comment by lubomirblazekcz** [comment]
@riderx @tony-scio any chance getting this merge request merged? This inded fixed our problem with redirect we had in our app, took as a whole day to debug that capacitor doesn't redirect 301, 302 urls on android :/

**Pull request closed without merging**
