### PR TITLE
[Bug]: add serial dispatch queue for `storedCalls` to avoid data-race

### PR DESCRIPTION
**Pull request by amitsingh19975**
Accessing `storedCalls` from two different threads causes crash since `Dictionary` is not thread safe that introduces data-race. The serial queue prevents the access to the shared resource by two different threads by queuing the operation and invoking the functions one-by-one.

There is other option to avoid data-race using locks, and top of that, there are two types of locks that can be used here: `NSLock` and the other one is `OSAllocatedUnfairLock`, which is faster than the first one.

### CODE REVIEW

**Comment by Steven0351** [comment]
We have a [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) type that could be made `internal` instead of `private`. I prefer using locks to GCD for synchronization. `OSAllocatedUnfairLock` is only available for iOS 16 and up

**Comment by amitsingh19975** [comment]
> We have a [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) type that could be made `internal` instead of `private`. I prefer using locks to GCD for synchronization. `OSAllocatedUnfairLock` is only available for iOS 16 and up

I've got an implementation of the unfair lock using `os_unfair_lock_lock` if you would like I could share that.

**Comment by Steven0351** [comment]
I get that os_unfair_lock is more performant than NSLock, and I've seen and used the < iOS 16 implementations myself, but I made the conscious decision to not implement it that way in Capacitor because it's a bit of boiler plate that has to be maintained. 

Every maintainer on this project has varying levels of familiarity with Swift, so removing the need to juggle pointers and manual memory management, even if it is abstracted in such a way, is better to be avoided in my opinion. I find it doubtful that the impact on performance would be noticeable in a capacitor application.

**Comment by amitsingh19975** [comment]
Originally, I fixed the problem using `NSLock`, but I thought the Capacitor team wouldn't like that so I went with the dispatch queue. I could make the concurrent dictionary internal and use that if you're ok with that.

**Comment by markemer** [comment]
If [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) solves the problem, lets use that. Otherwise `NSLock` is probably the way to go.

**Comment by amitsingh19975** [comment]
> If [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) solves the problem, lets use that. Otherwise `NSLock` is probably the way to go.

We've to extend it to have some function for it to be fully compatible with the use case. Otherwise, we could add a single function that accepts a block, and you get full access to the object with a lock.

**Comment by Steven0351** [comment]
> > If [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) solves the problem, lets use that. Otherwise `NSLock` is probably the way to go.
> 
> We've to extend it to have some function for it to be fully compatible with the use case. Otherwise, we could add a single function that accepts a block, and you get full access to the object with a lock.

Let's just add the single function that accepts the block, its simpler.

**Comment by amitsingh19975** [comment]
> > > If [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) solves the problem, lets use that. Otherwise `NSLock` is probably the way to go.
> > 
> > 
> > We've to extend it to have some function for it to be fully compatible with the use case. Otherwise, we could add a single function that accepts a block, and you get full access to the object with a lock.
> 
> Let's just add the single function that accepts the block, its simpler.

What you plan to call that function? I've a few names from kotlin and other places like `run`, `apply`, `with` or `inner`.

**Comment by Steven0351** [comment]
> > > > If [ConcurrentDictionary](https://github.com/ionic-team/capacitor/blob/b32b5b17ed14bd43c846b3fcb930bfd88e245e40/ios/Capacitor/Capacitor/KeyValueStore.swift#L275) solves the problem, lets use that. Otherwise `NSLock` is probably the way to go.
> > > 
> > > 
> > > We've to extend it to have some function for it to be fully compatible with the use case. Otherwise, we could add a single function that accepts a block, and you get full access to the object with a lock.
> > 
> > 
> > Let's just add the single function that accepts the block, its simpler.
> 
> What you plan to call that function? I've a few names from kotlin and other places like `run`, `apply`, `with` or `inner`.

I personally like `with` or something like `withValue` or `withLock`. Since it's not going to be a public API its not a _huge_ deal, but @markemer may have an opinion here

**Comment by amitsingh19975** [comment]
I've replaced the uses of the dispatch queue with the concurrent dictionary.

**Review by markemer — APPROVED** [review]

**Review by Steven0351 — APPROVED** [review]

**Pull request merged**
