### PR TITLE
feat(android): add support to custom sound on Push Notifications

### PR DESCRIPTION
**Pull request by root14**
Hi,

i simply add the support of custom sound on notifications channels.

### CODE REVIEW

**Comment by root14** [comment]
Sure, i will work on that tomorrow :)

**Comment by highway11** [comment]
Is there any documentation how to accomplish this? I'm looking for a guide or information as to where to put the custom sound file, how to setup the channel, how to format the notification payload to use that channel/sound.

**Comment by root14** [comment]
Hi @highway11,

i'm sorry i don't work at this moment with capactior. I don't have the stuff to test and create a guide.

I'll try to help you with my memories.

On android you have to put your sound file in the res/raw of your android native project. Then capacitor provide somes methodes in the PushNotification plugin to create channels. In the createChannel you put an object that is a NotificationChannel interface that capacitor provide. This object have a sound property that is your sound's file name.

I remember when i init & register my devices i was checking the list of existing channel and creating it if my channels was not in the list.

You should depending on which api you are using add a channel_id property in your payload.

Generally with capacitor you can follow native android developper documentation and do the same things with capacitor API

With FCM see below:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
Legacy FCM API:
https://firebase.google.com/docs/cloud-messaging/http-server-ref


See all available method in PushNotification plugin :
https://capacitorjs.com/docs/apis/push-notifications#type-163350

interface NotificationChannel {
description ?: string;
id : string;
importance : any;
lightColor ?: string;
lights ?: boolean;
name : string;
sound ?: string;
vibration ?: boolean;
visibility ?: any;
}

**Comment by highway11** [comment]
Thanks for the info @root14. I was able to get it working based on the FCM documentation you linked as well as an example I found here: https://forum.ionicframework.com/t/custom-sound-for-android-push-notification-not-working-fcm/172874

In Android Studio I needed to drag the emergency.mp3 sound file to the android/app/res/raw folder (create raw folder if it doesn't exist)

Use the following to setup the PushNotification plugin:

```
PushNotifications.createChannel({
    description: "Emergency Notifications",
    id: "fcm_emergency_channel",
    importance: 5,
    lights: true,
    name: "Emergency Alert Channel",
    sound: "emergency.mp3",
    vibration: true,
    visibility: 1,
})
    .then(() => {
      console.log("push channel created: ");
    })
    .catch((error) => {
      console.error("push channel error: ", error);
    });
};
```

And to send a push notification using Firebase SDK on node.js I found I had to use admin.sendMulticast as admin.sendToDevice does not support the android/webpush/apns payload format:
```
const admin = require('firebase-admin');
let message={
        notification:{
            title: title,
            body: body,
        },
        android: {
            notification: {
                defaultSound: true,
                notificationCount: 1,
                sound: 'emergency.mp3',
                channelId: 'fcm_emergency_channel',
                icon:`${projectHost()}/android-chrome-192x192.png`,
            },
            ttl: 20000
        },
        webpush: {
            notification: {
                icon:`${projectHost()}/android-chrome-192x192.png`
                
            },
            fcm_options: {
                link: projectHost()     
            }

        },
        apns: {
            payload: {
                aps: {
                    sound: 'default'
                }
            }
        },
        tokens: tokens
    };

const response = await admin.messaging().sendMulticast(message);
```

**Pull request merged**
