### PR TITLE
fix(http): Add URLSearchParams support

### LINKED ISSUE #7032: bug: Capacitor Http and Native Bridge don't handle ReadableStream
### Capacitor Version

```
npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
```

### Platform(s)

iOS (only tested)

### Current Behavior

calling `fetch('url', { method: 'POST', body: new URLSearchParams([ ['foo', 1], ['bar', true] ])`

results in https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L475 `Request` being made with a body of `ReadableStream`

which is passed through `convertBody` https://github.com/ionic-team/capacitor/blob/main/core/native-bridge.ts#L54

onto `cap.nativePromise` which fails with a `DataCloneError: The object can not be cloned.` in `postToNative`

### Expected Behavior

you can call `fetch` with the first parameter being a string url and the body being in the second parameter

### Other Technical Details

`npm --version` output: `9.8.1`

`node --version` output: `18.18.0`

`pod --version` output (iOS issues only): `1.10.1`

### PR DESCRIPTION
**Pull request by philjones88**
fixes #7032

### CODE REVIEW

**Comment by philjones88** [comment]
Anyone? Contributions not welcome?

**Review by ItsChaceD — APPROVED** [review]
LGTM, thank you!

**Comment by philjones88** [comment]
@ItsChaceD thanks. do i need to try and do a v6 version?

**Comment by mr-matt-b** [comment]
@ItsChaceD Can we get this merged please? 

I've created another PR with these same changes for v6 if that was the blocking factor.

**Comment by jcesarmobile** [comment]
Can you send it to main branch instead of to 5.x? 

We cherry-pick main changes into 5.x after they get merged.

**Comment by DellanX** [comment]
Any movement on here? Parts of my Auth Flow are blocked by this issue, so I am definitely in need of this.

As always, I am willing to help as well.

**Pull request closed without merging**
