### PR TITLE
feat(android): move Config to be per-instance rather than a singleton

### PR DESCRIPTION
**Pull request by jcesarmobile**
equivalent of https://github.com/ionic-team/capacitor/commit/e9640689af31c62e6c2416f1f289b07231368cb8 for Android

Used a JSONObject instead of a JSON formatted string (what iOS does) because JSONObject can be created from a JSON formatted string already, and can also put values in a simpler way than a JSON formatted string.

thoughts @carlpoole @dwieeb?

### CODE REVIEW

**Comment by dwieeb** [comment]
I don't know either, other than passing in `config` for every log method call 🤮

**Comment by carlpoole** [comment]
I think it would be messy if we had a logger instance per Config instance so I'm thinking have `shouldLog` as a static global variable on Logger that can be set by doing something like

`Logger.enable()`

and making it an all or nothing thing. I don't like the idea of tying the logger to the config when there is a possibility of having multiple configs.

**Comment by jcesarmobile** [comment]
I've passed the config to logger on bridge init and now it works.

I've noticed that there is a "Starting BridgeActivity" log that is always displayed since it's logged before the config is set, but was also happening with previous implementation.

**Comment by carlpoole** [comment]
Looks good!

**Pull request merged**
